// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Officer struct {
	ID       int64
	Name     string
	Title    string
	Linkedin sql.NullString
	ImageUri sql.NullString
}
