// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createOfficer = `-- name: CreateOfficer :one
INSERT INTO officers (name, title, linkedin, image_uri)
VALUES ($1, $2, $3, $4)
RETURNING id, name, title, linkedin, image_uri
`

type CreateOfficerParams struct {
	Name     string
	Title    string
	Linkedin sql.NullString
	ImageUri sql.NullString
}

func (q *Queries) CreateOfficer(ctx context.Context, arg CreateOfficerParams) (Officer, error) {
	row := q.db.QueryRowContext(ctx, createOfficer,
		arg.Name,
		arg.Title,
		arg.Linkedin,
		arg.ImageUri,
	)
	var i Officer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Linkedin,
		&i.ImageUri,
	)
	return i, err
}

const deleteOfficer = `-- name: DeleteOfficer :exec
DELETE FROM officers WHERE id = $1
`

func (q *Queries) DeleteOfficer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOfficer, id)
	return err
}

const getOfficer = `-- name: GetOfficer :one
SELECT id, name, title, linkedin, image_uri FROM officers WHERE id = $1
`

func (q *Queries) GetOfficer(ctx context.Context, id int64) (Officer, error) {
	row := q.db.QueryRowContext(ctx, getOfficer, id)
	var i Officer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Linkedin,
		&i.ImageUri,
	)
	return i, err
}

const listOfficers = `-- name: ListOfficers :many
SELECT id, name, title, linkedin, image_uri FROM officers ORDER BY id
`

func (q *Queries) ListOfficers(ctx context.Context) ([]Officer, error) {
	rows, err := q.db.QueryContext(ctx, listOfficers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Officer
	for rows.Next() {
		var i Officer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Linkedin,
			&i.ImageUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
